disabled = false
languageCode = "en"
languageName = "English"
weight = 1
title = "ijjtech"

[params]
displayName = "EN"
isoCode = "en"
rtl = false
dateFormat = "2 January 2006"
logo = ""
  [params.author]
    image="headshot.JPG"
    name = "Ian Jones"
    links = [ { github = "https://github.com/eonloop" }, { linkedin = "https://www.linkedin.com/in/ianj1993/" } ]
    headline = "Building Better Systems Through Documentation and Code"

